//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vobla.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vobla.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as:.
        /// </summary>
        public static string AccountLoggedAs {
            get {
                return ResourceManager.GetString("AccountLoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AccountLoginButton {
            get {
                return ResourceManager.GetString("AccountLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string AccountLoginEmailLabel {
            get {
                return ResourceManager.GetString("AccountLoginEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountLoginPWLabel {
            get {
                return ResourceManager.GetString("AccountLoginPWLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string AccountLogoutButton {
            get {
                return ResourceManager.GetString("AccountLogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link was put into your clipboard..
        /// </summary>
        public static string BalloontipUploadedText {
            get {
                return ResourceManager.GetString("BalloontipUploadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded.
        /// </summary>
        public static string BalloontipUploadedTitle {
            get {
                return ResourceManager.GetString("BalloontipUploadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has not been uploaded to the server..
        /// </summary>
        public static string BalloontipUploadErrorText {
            get {
                return ResourceManager.GetString("BalloontipUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload error.
        /// </summary>
        public static string BalloontipUploadErrorTitle {
            get {
                return ResourceManager.GetString("BalloontipUploadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon32 {
            get {
                object obj = ResourceManager.GetObject("Icon32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon64 {
            get {
                object obj = ResourceManager.GetObject("Icon64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string NotifyExit {
            get {
                return ResourceManager.GetString("NotifyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string NotifyOpenDashboard {
            get {
                return ResourceManager.GetString("NotifyOpenDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NotifySettings {
            get {
                return ResourceManager.GetString("NotifySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vobla.
        /// </summary>
        public static string NotifyText {
            get {
                return ResourceManager.GetString("NotifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vobla.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
    }
}
